### ISSUE TITLE
redis.trib.rb is replaced with redis-cli

### ISSUE THREAD

**Issue by FZambia** [Grokzen/travis-redis-cluster#1]
Hello, thanks for this repo! I just came across it and noticed that redis.trib.rb is deprecated, see commit https://github.com/antirez/redis/commit/d222eda9f089f6605d755777c32132cb8cad76c9

**Comment by Grokzen** [comment]
Yeah... this repo is not really active any longer, i probably will put it in maintenence mode and you can just look over at Grokze/docker-redis-cluster repo instead for a more updated version that solved this problem ages ago.
